default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: cr_development

test:
  <<: *default
  database: cr_test

production:
  <<: *default
  database: cr_production
